var data = [{
  
  'name': 'Gondola',
  'logo': 'assets/images/logo-gondola.jpg',
  'image': 'assets/images/food-gondola.jpg',
  'local': 'assets/images/restaurante-gondola.jpg',
  'district': 'La Molina',
  'address': 'Maria Auxiliadora 453',
  'price': '$30',
  'type': 'Pescados y Mariscos',
},
{
  'name': 'La Casona',
  'logo': 'assets/images/logo-la-casona.jpg',
  'image': 'assets/images/food-la-casona.jpg',
  'local': 'assets/images/restaurante-la-casona.jpg',
  'district': 'Villa Maria',
  'address': 'Av. Villarán 759',
  'price': ' $100 - $158',
  'type': 'Parrilla',
},
{
  'name': 'Mr Chilon',
  'logo': 'assets/images/logo-mr-chilon.jpg',
  'image': 'assets/images/food-mr-chilon.jpg',
  'local': 'assets/images/restaurante-mr-chilon.jpg',
  'district': 'San Isidro',
  'address': 'Av. Rinconada del Lago 654',
  'money': ' $45 - $80',
  'type': 'Tacos',
},
{
  'name': 'La Fogata',
  'logo': 'assets/images/logo-la-fogata.jpg',
  'image': 'assets/images/food-la-fogata.jpg',
  'local': 'assets/images/restaurante-la-fogata.jpg',
  'district': 'Miraflores',
  'address': 'Calle Benavides 397',
  'price': ' $80',
  'type': 'Parrilla',
},
{
  'name': 'Gusto',
  'logo': 'assets/images/logo-gusto.jpg',
  'image': 'assets/images/food-gusto.jpg',
  'local': 'assets/images/restaurante-gusto.jpg',
  'district': 'Barranco',
  'address': 'Av Benavides 1180',
  'price': ' $40',
  'type': 'Comida China',
},
{
  'name': 'Peru Sabe',
  'logo': 'assets/images/logo-peru-sabe.jpg',
  'image': 'assets/images/food-peru-sabe.jpg',
  'local': 'assets/images/restaurante-peru-sabe.jpg',
  'district': 'San Martin',
  'address': 'Av. La Molina 1284',
  'price': ' $180 - $220',
  'type': 'Comida Criolla',
}
];
